"""
Script for testing the behavior of the SimpleModel class.

Test naming convention:
    test_[the name of the tested method]_[expected input / tested state]_[expected behavior]
"""
import numpy as np
import numpy.testing as npt
from PATE.Teacher import Teacher
from PATE.Base.SimpleModel import SimpleModel

# Private data used to train Teacher models
X_private = np.random.random((200, 12))
y_private = np.random.random((200))

# Public data used to train Student model, y_public is generated by Teacher models
X_public = np.random.random((20, 12))

teachers = Teacher(SimpleModel, epochs=10, n_teachers=10,
                   verbose=True, n_classes=10, epsilon=1)
teachers.fit(X_private, y_private)

predictions = teachers.predict()


# class TestSimpleModel:
#     def 